package com.example.demo;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class ExampleController {

    @RequestMapping("/")
    public String welcome(Model model)
    {
        model.addAttribute("german", "of executable JAR with JSPs generated by gradle!");
        return "index";
    }


}
